<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331175116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price INT NOT NULL, billing_interval VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE app_subscription ADD plan_id INT NOT NULL');
        $this->addSql('ALTER TABLE app_subscription ADD CONSTRAINT FK_61487E52E899029B FOREIGN KEY (plan_id) REFERENCES plan (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_61487E52E899029B ON app_subscription (plan_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE plan');
        $this->addSql('ALTER TABLE app_subscription DROP CONSTRAINT FK_61487E52E899029B');
        $this->addSql('DROP INDEX IDX_61487E52E899029B');
        $this->addSql('ALTER TABLE app_subscription DROP plan_id');
    }
}
