<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331174652 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, current_period_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, current_period_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE subscription_user (subscription_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (subscription_id, user_id))');
        $this->addSql('CREATE INDEX IDX_BAAFC6579A1887DC ON subscription_user (subscription_id)');
        $this->addSql('CREATE INDEX IDX_BAAFC657A76ED395 ON subscription_user (user_id)');
        $this->addSql('ALTER TABLE subscription_user ADD CONSTRAINT FK_BAAFC6579A1887DC FOREIGN KEY (subscription_id) REFERENCES app_subscription (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subscription_user ADD CONSTRAINT FK_BAAFC657A76ED395 FOREIGN KEY (user_id) REFERENCES "app_user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_user ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE app_user ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE subscription_user DROP CONSTRAINT FK_BAAFC6579A1887DC');
        $this->addSql('ALTER TABLE subscription_user DROP CONSTRAINT FK_BAAFC657A76ED395');
        $this->addSql('DROP TABLE app_subscription');
        $this->addSql('DROP TABLE subscription_user');
        $this->addSql('ALTER TABLE "app_user" DROP created_at');
        $this->addSql('ALTER TABLE "app_user" DROP updated_at');
    }
}
